imports_granularity = "Crate"
group_imports = "One"
comment_width = 100
format_code_in_doc_comments = true
imports_layout = "Vertical"
error_on_unformatted = true
wrap_comments = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
max_width = 100
chain_width = 100
array_width = 100